package com.mark.test.framework.web.dao;


import com.mark.test.framework.web.dto.GwTransfers;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

@Repository
public interface GwTransfersMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    @Delete({
        "delete from gw_transfers",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    @Insert({
        "insert into gw_transfers (id, request_no, ",
        "channel_code, gw_request_no, ",
        "main_account_no, pay_account_no, ",
        "tran_type, status, ",
        "gw_status, recv_account_no, ",
        "recv_account_name, tran_amount, ",
        "remark, err_code, ",
        "err_msg, create_time, ",
        "update_time, request_time, ",
        "finish_time, recv_bankcode, ",
        "recv_tgfi, recv_banknm)",
        "values (#{id,jdbcType=BIGINT}, #{requestNo,jdbcType=VARCHAR}, ",
        "#{channelCode,jdbcType=VARCHAR}, #{gwRequestNo,jdbcType=VARCHAR}, ",
        "#{mainAccountNo,jdbcType=VARCHAR}, #{payAccountNo,jdbcType=VARCHAR}, ",
        "#{tranType,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{gwStatus,jdbcType=VARCHAR}, #{recvAccountNo,jdbcType=VARCHAR}, ",
        "#{recvAccountName,jdbcType=VARCHAR}, #{tranAmount,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR}, #{errCode,jdbcType=VARCHAR}, ",
        "#{errMsg,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{requestTime,jdbcType=TIMESTAMP}, ",
        "#{finishTime,jdbcType=TIMESTAMP}, #{recvBankcode,jdbcType=VARCHAR}, ",
        "#{recvTgfi,jdbcType=VARCHAR}, #{recvBanknm,jdbcType=VARCHAR})"
    })
    int insert(GwTransfers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    int insertSelective(GwTransfers record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, request_no, channel_code, gw_request_no, main_account_no, pay_account_no, ",
        "tran_type, status, gw_status, recv_account_no, recv_account_name, tran_amount, ",
        "remark, err_code, err_msg, create_time, update_time, request_time, finish_time, ",
        "recv_bankcode, recv_tgfi, recv_banknm",
        "from gw_transfers",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    GwTransfers selectByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GwTransfers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_transfers
     *
     * @mbggenerated
     */
    @Update({
        "update gw_transfers",
        "set request_no = #{requestNo,jdbcType=VARCHAR},",
          "channel_code = #{channelCode,jdbcType=VARCHAR},",
          "gw_request_no = #{gwRequestNo,jdbcType=VARCHAR},",
          "main_account_no = #{mainAccountNo,jdbcType=VARCHAR},",
          "pay_account_no = #{payAccountNo,jdbcType=VARCHAR},",
          "tran_type = #{tranType,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "gw_status = #{gwStatus,jdbcType=VARCHAR},",
          "recv_account_no = #{recvAccountNo,jdbcType=VARCHAR},",
          "recv_account_name = #{recvAccountName,jdbcType=VARCHAR},",
          "tran_amount = #{tranAmount,jdbcType=DECIMAL},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "err_code = #{errCode,jdbcType=VARCHAR},",
          "err_msg = #{errMsg,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "request_time = #{requestTime,jdbcType=TIMESTAMP},",
          "finish_time = #{finishTime,jdbcType=TIMESTAMP},",
          "recv_bankcode = #{recvBankcode,jdbcType=VARCHAR},",
          "recv_tgfi = #{recvTgfi,jdbcType=VARCHAR},",
          "recv_banknm = #{recvBanknm,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GwTransfers record);
}