package com.mark.test.framework.api.dto;

import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.Date;

public class OpenAgreementDetermine {

    public OpenAgreementDetermine() {
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.orderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.reqNo
     *
     * @mbggenerated
     */
    private String reqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.customerId
     *
     * @mbggenerated
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.smsSeq
     *
     * @mbggenerated
     */
    private String smsseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.authCode
     *
     * @mbggenerated
     */
    private String authcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.custAccountId
     *
     * @mbggenerated
     */
    private String custaccountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.holderName
     *
     * @mbggenerated
     */
    private String holdername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.bankCardNo
     *
     * @mbggenerated
     */
    private String bankcardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.treatyNo
     *
     * @mbggenerated
     */
    private String treatyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.failureDetails
     *
     * @mbggenerated
     */
    private String failuredetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.errorCode
     *
     * @mbggenerated
     */
    private String errorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.sendDate
     *
     * @mbggenerated
     */
    private Date senddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.returnDate
     *
     * @mbggenerated
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.updateDate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_agreement_determine.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.orderNo
     *
     * @return the value of open_agreement_determine.orderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.reqNo
     *
     * @return the value of open_agreement_determine.reqNo
     *
     * @mbggenerated
     */
    public String getReqno() {
        return reqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.customerId
     *
     * @return the value of open_agreement_determine.customerId
     *
     * @mbggenerated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.smsSeq
     *
     * @return the value of open_agreement_determine.smsSeq
     *
     * @mbggenerated
     */
    public String getSmsseq() {
        return smsseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.authCode
     *
     * @return the value of open_agreement_determine.authCode
     *
     * @mbggenerated
     */
    public String getAuthcode() {
        return authcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.custAccountId
     *
     * @return the value of open_agreement_determine.custAccountId
     *
     * @mbggenerated
     */
    public String getCustaccountid() {
        return custaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.holderName
     *
     * @return the value of open_agreement_determine.holderName
     *
     * @mbggenerated
     */
    public String getHoldername() {
        return holdername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.bankCardNo
     *
     * @return the value of open_agreement_determine.bankCardNo
     *
     * @mbggenerated
     */
    public String getBankcardno() {
        return bankcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.status
     *
     * @return the value of open_agreement_determine.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.treatyNo
     *
     * @return the value of open_agreement_determine.treatyNo
     *
     * @mbggenerated
     */
    public String getTreatyno() {
        return treatyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.failureDetails
     *
     * @return the value of open_agreement_determine.failureDetails
     *
     * @mbggenerated
     */
    public String getFailuredetails() {
        return failuredetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.errorCode
     *
     * @return the value of open_agreement_determine.errorCode
     *
     * @mbggenerated
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.sendDate
     *
     * @return the value of open_agreement_determine.sendDate
     *
     * @mbggenerated
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.returnDate
     *
     * @return the value of open_agreement_determine.returnDate
     *
     * @mbggenerated
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.updateDate
     *
     * @return the value of open_agreement_determine.updateDate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_agreement_determine.source
     *
     * @return the value of open_agreement_determine.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }


    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    public void setReqno(String reqno) {
        this.reqno = reqno;
    }

    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    public void setSmsseq(String smsseq) {
        this.smsseq = smsseq;
    }

    public void setAuthcode(String authcode) {
        this.authcode = authcode;
    }

    public void setCustaccountid(String custaccountid) {
        this.custaccountid = custaccountid;
    }

    public void setHoldername(String holdername) {
        this.holdername = holdername;
    }

    public void setBankcardno(String bankcardno) {
        this.bankcardno = bankcardno;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setTreatyno(String treatyno) {
        this.treatyno = treatyno;
    }

    public void setFailuredetails(String failuredetails) {
        this.failuredetails = failuredetails;
    }

    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(OpenAgreementDetermine.this);
    }
}