package com.mark.test.framework.core.dao;


import com.mark.test.framework.api.dto.OpenAgreementDetermine;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

@Repository
public interface OpenAgreementDetermineMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    @Delete({
        "delete from open_agreement_determine",
        "where orderNo = #{orderno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orderno);


    @Delete({
            "delete from open_agreement_determine",
            "where customerId = #{customerId,jdbcType=VARCHAR}"
    })
    int deleteByUserId(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    @Insert({
        "insert into open_agreement_determine (orderNo, reqNo, ",
        "customerId, smsSeq, ",
        "authCode, custAccountId, ",
        "holderName, bankCardNo, ",
        "status, treatyNo, ",
        "failureDetails, errorCode, ",
        "sendDate, returnDate, ",
        "updateDate, source)",
        "values (#{orderno,jdbcType=VARCHAR}, #{reqno,jdbcType=VARCHAR}, ",
        "#{customerid,jdbcType=VARCHAR}, #{smsseq,jdbcType=VARCHAR}, ",
        "#{authcode,jdbcType=VARCHAR}, #{custaccountid,jdbcType=VARCHAR}, ",
        "#{holdername,jdbcType=VARCHAR}, #{bankcardno,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{treatyno,jdbcType=VARCHAR}, ",
        "#{failuredetails,jdbcType=VARCHAR}, #{errorcode,jdbcType=VARCHAR}, ",
        "#{senddate,jdbcType=TIMESTAMP}, #{returndate,jdbcType=TIMESTAMP}, ",
        "#{updatedate,jdbcType=TIMESTAMP}, #{source,jdbcType=VARCHAR})"
    })
    int insert(OpenAgreementDetermine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    int insertSelective(OpenAgreementDetermine record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "orderNo, reqNo, customerId, smsSeq, authCode, custAccountId, holderName, bankCardNo, ",
        "status, treatyNo, failureDetails, errorCode, sendDate, returnDate, updateDate, ",
        "source",
        "from open_agreement_determine",
        "where orderNo = #{orderno,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    OpenAgreementDetermine selectByPrimaryKey(String orderno);


    @Select({
            "select",
            "orderNo, reqNo, customerId, smsSeq, authCode, custAccountId, holderName, bankCardNo, ",
            "status, treatyNo, failureDetails, errorCode, sendDate, returnDate, updateDate, ",
            "source",
            "from open_agreement_determine",
            "where customerId = #{customerId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    OpenAgreementDetermine selectByCustomerId(String customerId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OpenAgreementDetermine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_agreement_determine
     *
     * @mbggenerated
     */
    @Update({
        "update open_agreement_determine",
        "set reqNo = #{reqno,jdbcType=VARCHAR},",
          "customerId = #{customerid,jdbcType=VARCHAR},",
          "smsSeq = #{smsseq,jdbcType=VARCHAR},",
          "authCode = #{authcode,jdbcType=VARCHAR},",
          "custAccountId = #{custaccountid,jdbcType=VARCHAR},",
          "holderName = #{holdername,jdbcType=VARCHAR},",
          "bankCardNo = #{bankcardno,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "treatyNo = #{treatyno,jdbcType=VARCHAR},",
          "failureDetails = #{failuredetails,jdbcType=VARCHAR},",
          "errorCode = #{errorcode,jdbcType=VARCHAR},",
          "sendDate = #{senddate,jdbcType=TIMESTAMP},",
          "returnDate = #{returndate,jdbcType=TIMESTAMP},",
          "updateDate = #{updatedate,jdbcType=TIMESTAMP},",
          "source = #{source,jdbcType=VARCHAR}",
        "where orderNo = #{orderno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OpenAgreementDetermine record);
}