#mysqldb:
#  image: mysql
#  environment:
#   MYSQL_DATABASE: sample
#   MYSQL_USER: mysql
#   MYSQL_PASSWORD: mysql
#   MYSQL_ROOT_PASSWORD: supersecret
#
#mywildfly:
#	image: wildfly-mysql-javaee7
#	links:
#		- mysqldb:db
#	ports:
#		- 8080


executer:
    image: tomcat-mark:0.1
    ports:
        - "8123:8080"
